services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    networks:
      - app-network
    restart: unless-stopped
  mail-dev:
    container_name: maildev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - app-network

  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.3
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - app-network
    command:
      - "start-dev"

volumes:
  postgres:
    driver: local
networks:
  app-network:
    driver: bridge